# Site settings
course_name: "EE 274: Data Compression, Theory and Applications"
course_description: ""
course_semester: "Fall 2022-23"

baseurl: '/Fall22' #"/EE274" # the subpath of your site, e.g. /blog/
url: "http://StanfordDataCompressionClass.github.io/" #"http://tpulkit.github.io/" # the base hostname & protocol for your site

#schoolname: "Stanford University"
#schoolurl: "https://stanford.edu"
#twitter_username: username

#address: |
#    School of Witchcraft and Wizardry
#    Hogwarts
#    Scotland

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X
google_analytics: G-16WVC7K0TB

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: true


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
